language: python
python:
  - '2.7'
cache:
  directories:
    - $HOME/.pip-cache
env:
  global:
    - PYTEST_OPTS="--pep8 --cov oscar_mws"
    - PIP_OPTS="--download-cache $HOME/.pip-cache"

    # AWS credentials for MWS (open source test account)
    - secure: "iYRLQPabW/4+tigVu28V/J/92RJw/hOUfNXk0+XBQ2ZcQLUY6J4Haq7e5PYaod88dUk9T7qPoE6R2huOCK/EvbREWIv+1ngpzpvsar5c4R3ViviticZBOkzWEsFigfYt4xt4eV08F56aQmULV0763WqRUKHOnDBPrm+B+P1WGIM="
    - secure: "h1U+X5XqOIK/xK1A0GPHbFqZr68FNY3HqIYJIIezkOkFs8PvKyZFNxnBfYuixglikIhOnwgGyFAe1IvRmdNxB7yyNNJX3raTux5qlTsWGwA7EHr0wi74y9EhFYWv4tTdvneMXs3uJ4tvcziSpOdFY4JgMDLG7+8tQoi3TGKBl+M="
    - secure: "FDDaeoEuenAbKsPkPue9Pc/summYE2xgEKGeyGaEwngXmAFAjpzKt8WGGekDyvUEemJ6+OKcCPQJJTIfm2rBI4Bp+32LwCp9hrfMHsJeaxCjpjj9XHmODLpYm88am0ANq4lhw8nXLc2EeA91tVZsLtLCoymIbTOJYBJqRbvDJnc="

  matrix:
    - DJANGO_VERSION=">=1.4,<1.5"
    - DJANGO_VERSION=">=1.5,<1.6"
    - DJANGO_VERSION=">=1.6,<1.7"
    - DJANGO_VERSION=">=1.6,<1.7" PYTEST_OPTS="-m integration"
install:
  - pip install $PIP_OPTS Django$DJANGO_VERSION
  - pip install $PIP_OPTS .
  - pip install $PIP_OPTS -r requirements.txt
script:
  - py.test $PYTEST_OPTS
after_success:
  - coveralls
